### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by vogt31337** [ttinoco/OPTALG#3]
Hi,

is it possible to get a Python 3 compatible version?
During install I get around 8 "print" errors with python 3.

Thx!

**Comment by martinzellner** [comment]
There is an attempt to make OPTALG Python 3 compatible in the [python-3 branch ](https://github.com/ttinoco/OPTALG/tree/python-3) of this project.
Maybe this helps.

**Comment by ttinoco** [comment]
Yes, we can do that. I will work on this and make the master branch python
3 compatible. I will notify here as soon as this is done.

**Comment by vogt31337** [comment]
Nice thanks! The Python-3 branch doesn't work or I've made something else wrong:

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\opt_solver\augl.py to augl.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\opt_solver\augl.py", line 135
    print '\nSolver: augL'
                         ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\opt_solver\iqp.py to iqp.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\opt_solver\iqp.py", line 183
    print '\nSolver: IQP'
                        ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\opt_solver\lccp.py to lccp.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\opt_solver\lccp.py", line 171
    print '\nSolver: LCCP'
                         ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\opt_solver\nr.py to nr.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\opt_solver\nr.py", line 95
    print '\nSolver: NR'
                       ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_grad.py to stoch_grad.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_grad.py", line 22
    print '\nStochastic Gradient'
                                ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_grad_pd.py to stoch_grad_pd.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_grad_pd.py", line 22
    print '\nPrimal-Dual Stochastic Gradient'
                                            ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_hyb.py to stoch_hyb.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_hyb.py", line 23
    print '\nStochastic Hybrid'
                              ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_hyb_pd.py to stoch_hyb_pd.cpython-35.pyc
  File "C:\Anaconda3\Lib\site-packages\optalg\stoch_solver\stoch_hyb_pd.py", line 24
    print '\nPrimal-Dual Stochastic Hybrid'
                                          ^
SyntaxError: Missing parentheses in call to 'print'

running install_egg_info
Removing C:\Anaconda3\Lib\site-packages\OPTALG-1.0-py3.5.egg-info
Writing C:\Anaconda3\Lib\site-packages\OPTALG-1.0-py3.5.egg-info

**Comment by martinzellner** [comment]
This looks like a caching issue to me. If you look at [line 135 in augl.py](https://github.com/ttinoco/OPTALG/blob/python-3/optalg/opt_solver/augl.py#L137) the print is correct.

**Comment by vogt31337** [comment]
I had to delete manually the folder in my anaconda and then it worked. Thanks for the hint!
